Normalise the logging with other services.
JSainsburyPLC/xecho pull request #4
Opened 2019-09-27 11:45 UTC by KevinJCross

- The app field is application in all the other services so we should use that.
- Build version should be logged at startup and is not needed for each log statement.

We need to consolidate our logging style with the other services to make debugging  service to service and tracing easier.

2019-09-27 14:04 UTC, steinfletcher commented
All looks good. You might want to check with George before removing the build version since he added it recently. I think it's quite useful.

2019-09-30 14:49 UTC, webbgeorge requested changes

2019-09-30 14:49 UTC, gaw508 commented on logging.go
> -		"build_version": buildVersion,
The build version is in every log message because when we start doing canary deployments, it is useful to check logs for one variant vs another.

2019-09-30 14:49 UTC, gaw508 commented on app.go
> +			"project":       conf.ProjectName,
project not required

2019-09-30 14:49 UTC, gaw508 commented on app.go
> +			"hostname":      getHostName(),
should add hostname to request level logging too.

2019-11-19 17:30 UTC, closed without merging